### PR TITLE
get displayed data on zoom.

### PR DESCRIPTION
**Pull request by azulay7**
need to declare funcion on config that get current data

### CODE REVIEW

**Comment by jpetitcolas** [comment]
What is your use case?

**Comment by azulay7** [comment]
As I mentioned in the title. I would like get the current data that displayed,  and also the current time range.

**Comment by jpetitcolas** [comment]
I am currently working on a PR which should fix the issue without having to specify a new configuration function to retrieve already configured data. See https://github.com/marmelab/EventDrops/pull/151 as a reference. 

I think it should fix your issue: https://github.com/marmelab/EventDrops/pull/151/files#diff-d48a18b6fef4f6aa6ba8f5b999f9ebd7R105

``` js

**Comment by jpetitcolas** [comment]
PR has been merged. Closing your PR. Feel free to re-open an issue if it doesn't fill your usecase. :)

**Pull request closed without merging**
