### PR TITLE
Add support for typescript and common.js import syntax .

### PR DESCRIPTION
**Pull request by osadan**
I want to be able to debug eventdrops inside my host app. 
so I made few changes 

1. To support type script.
2. To support import statement inside of webpack bundling with Common.js syntax 
3. To be able to debug the code inside the host 

this way I am able to debug and develop to eventdrops inside my host . 
with no need to deploy on every change.

### CODE REVIEW

**Comment by osadan** [comment]
I also created https://github.com/marmelab/configurable.js/pull/7 and https://github.com/marmelab/configurable.js/pull/6 in order to support this capability

**Comment by osadan** [comment]
the test's fails because the node version does not aware about Object.assign function

**Comment by jpetitcolas** [comment]
Can you try to rebase? Tests are fine on master.

**Comment by jpetitcolas** [comment]
I see a lot of commits, some of them not related to TypeScript. Can you please split this PR in several ones with each one having a specific topic? :)

And it needs rebase again. Sorry about that. :/

**Comment by jpetitcolas** [comment]
We released a major version, hence this PR would be difficult to merge/rebase. Can you open a new one if you still need to support typescript?

**Pull request closed without merging**
