### PR TITLE
[RFR] Color by point

### PR DESCRIPTION
**Pull request by ThieryMichel**
- [x] add colorEvent config
- [x] add example
- [x] verify performance quality

### CODE REVIEW

**Comment by fzaninotto** [comment]
I'm afraid this will be very hard on performances...

**Comment by ThieryMichel** [comment]
I updated the example to use the new feature.
I did not see any impact on my laptop, granted he is quite powerful. Will test it on a less powerful one.

**Comment by ThieryMichel** [comment]
Still no difference in performance on my old laptop. I think this will pose no problem.

**Comment by ThieryMichel** [comment]
see #16

**Pull request merged**
