### PR TITLE
[RFR] EventDrops rewriting

### LINKED ISSUE #136: minimum and maximum dates won't update on zooming
I just git clone the project (0.3.0-alpha) and run the demo.
the bug occurs there.

### PR DESCRIPTION
**Pull request by jpetitcolas**
Fixes #136.

Current implementation of EventDrops is quite difficult to read and understand. Moreover, it doesn't use D3 powerful `data()` feature enough. Hence, to ensure a better maintenance, I started this rewrite from scratch.

I am going to introduce several BC changes, especially in regard to configuration, to group more logically all related configuration parameters (for instance, `drop.color` and `drop.radius`).

### Todos

* [x] Fix zoom center position
* [x] Find a way to expose date bounds and filtered datas
* [x] Update README
* [x] Write upgrade guide for < 4 version users
* [x] Write tests

### CODE REVIEW

**Comment by jpetitcolas** [comment]
We should be close of current version now. I updated the missing todos in the first post. 

eventdrops

Note I removed `configurable.js`. We won't be able to tune configuration calling methods once the app has been created. Instead, we pass an array of options in the constructor. Indeed, it felt less intuitive for second levels properties (for instance, tuning `metaballs.blurDeviation`).

**Comment by fzaninotto** [comment]
Great work!

But it's still missing the most important part... The blobs. I'm afraid that the perf will drop once you add it.

**Comment by jpetitcolas** [comment]
Metaballs are already here. Performances are still far better even with it. 

For API, everything changed. I'll probably write a dedicated "UPGRADE-4.md" file.

**Comment by jpetitcolas** [comment]
Missing configuration parameters to reimplement:


  - `locale`: locale used for the X axis labels. See [d3.locale](https://github.com/mbostock/d3/wiki/Localization#locale) for the expected format. Defaults to null (i.e. d3 default locale).
  - `axisFormat`: function receiving the d3 axis object, to customize tick number and size.
  - `tickFormat`: tickFormat for the X axis. See [d3.timeFormat.multi()](https://github.com/mbostock/d3/wiki/Time-Formatting#format_multi) for expected format.
  - `mouseover`: function to be called when hovering an event in the chart. Receives the DOM element hovered (uses event delegation). Default: `() => {}`.
  - `click`: function to be called on click event of data-point (circle). Receives the DOM element hovered (uses event delegation). Default: `() => {}`.
  - `hasDelimiter`: whether to draw time boundaries on top of the chart. Defaults to `true`.
  - `hasTopAxis`: whether the chart has a top X axis. Accepts both a boolean or a function receiving the data of the graph that returns a boolean.
  - `hasBottomAxis`: same as topAxis but for the bottom X axis
  - `minScale`: The minimum scaling (zoom out), default to `0`.
  - `maxScale`: The maximum scaling (zoom in), default to `Infinity`.
  - `mouseout`: event handler to execute when mouse leave a drop. Default: `() => {}`.
  - `date`: function that returns the date from each data point when passing objects. Defaults to `d=>d`.

**Pull request merged**
