### PR TITLE
[RFR] Package cleanup

### PR DESCRIPTION
**Pull request by deevus**
Greetings

First of all, great work! We love the idea of this and we think we can make good use of the graph.

Secondly, we've already started working with it but have had some difficulty getting up and running due to some meta issues with the package. 

- Storing the build artifacts in git means that the source code and distribution code will likely be out of sync. We ran into this while trying to debug some issues. 
- Style loader configuration was breaking on Windows.
- We don't use `make` so converting the Makefile tasks to `npm scripts` was a no brainer (and very simple). 

I also fixed some linter errors that were breaking given the `.eslintrc` file. There are likely others in other files, but I did this as I was working. 

Please let me know if there are any issues with the changes. I'd be happy to bring them more in line with the ethos of the project if required.

### CODE REVIEW

**Comment by jpetitcolas** [comment]
Thanks for your PR! It looks great! :)

However, I'm wondering how the build process (and especially npm publication) would work if we don't commit the built files? We should take a look on it. A link quickly found on Google: https://medium.com/@kentcdodds/why-i-don-t-commit-generated-files-to-master-a4d76382564#.kwf37lxve

Meanwhile, can you revert the `dist` changes? We will then be able to merge your PR.

**Comment by jpetitcolas** [comment]
Note: I prefixed your PR with [RFR] (Ready for Review). We use this label and [WIP] (Work In Progress) to better track PR progression.

**Comment by deevus** [comment]
You're already using Travis CI, so perhaps this might help: https://docs.travis-ci.com/user/deployment/npm#Releasing-build-artifacts

Essentially, you would build the project first (generating `dist/`), then publish to npm

**Comment by deevus** [comment]
Updated as requested

**Comment by jpetitcolas** [comment]
You missed the two deleted JS files. :)

**Comment by deevus** [comment]
Check again. I did it wrong the first time :)

**Pull request merged**
